In [ ]:
import os 
os.chdir('/content/drive/MyDrive/DeepLearningColab/Pytorch_Basics')

In [ ]:
pwd

'/content/drive/MyDrive/DeepLearningColab/Pytorch_Basics'

In [ ]:
import torch
import numpy as np

In [ ]:
# Tensor initialization
  # --> Dtype
  # --> Device - cpu or gpu
  # --> requires _ grad --> gradient decent , during back prop

# This line repesents that if your system has gpu it will be used else cpu 
# Makes your code work in both condition
device = 'cuda' if torch.cuda.is_available() else 'cpu'

tensor = torch.tensor([[1,2,3],[1,2,3]],
                      dtype=torch.float,
                      device=device,requires_grad = True)


print(tensor)
print(tensor.dtype)
# default 0 means 1 gpu 
print(tensor.device)
print(tensor.shape)
print(tensor.requires_grad)

tensor([[1., 2., 3.],
        [1., 2., 3.]], device='cuda:0', requires_grad=True)
torch.float32
cuda:0
torch.Size([2, 3])
True


In [ ]:
# Other common initialization

# empty will create space of size with random values 
x = torch.empty(size=(3,3))
print(x)

# Zeros
x = torch.zeros(size=(3,3))
print(x)

# ones
x = torch.ones(size=(3,3))
print(x)

# random
x = torch.rand(size=(3,3))
print(x)

# eye identity matrix
x = torch.eye(3)
print(x)

# eye identity matrix
x = torch.arange(start=0,end=5,step=1)
print(x)

# eye identity matrix
x = torch.linspace(start=1,end=10,steps=11)
print(x)

# eye identity matrix
x = torch.eye(3)
print(x)

# empty with normal and uniform 
x = torch.empty(size=(3,3)).normal_(mean=0,std=1)
print(x)

x = torch.empty(size=(3,3)).uniform_()
print(x)

# diagnal matrix 
x = torch.diag(torch.ones(10))
print(x)

tensor([[-1.8201e-03,  3.0721e-41,  3.3631e-44],
        [ 0.0000e+00,         nan,  3.0721e-41],
        [ 1.1578e+27,  1.1362e+30,  7.1547e+22]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3574, 0.5665, 0.5481],
        [0.1781, 0.6827, 0.1490],
        [0.6071, 0.4483, 0.0266]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([0, 1, 2, 3, 4])
tensor([ 1.0000,  1.9000,  2.8000,  3.7000,  4.6000,  5.5000,  6.4000,  7.3000,
         8.2000,  9.1000, 10.0000])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[ 0.8118, -0.8655, -1.3193],
        [ 0.7292,  1.6709,  0.4414],
        [ 0.3289,  0.5014,  2.3698]])
tensor([[0.3564, 0.1291, 0.7321],
        [0.1950, 0.2774, 0.6381],
        [0.8639, 0.8832, 0.6554]])
tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0

In [ ]:
# How to convert tensor to different data types(int,float,double)
x = torch.arange(4)
print(x.bool())
print(x.int())
print(x.short()) # int16
print(x.long())  # int64
print(x.half())  # float 16
print(x.float()) # float 32
print(x.double())# float 64

tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int32)
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [ ]:
# How to convert from numpy to tensor

np_array = np.array([[1,2,3],[4,5,6]])
print(np_array)

tensor = torch.from_numpy(np_array)
print(tensor)

[[1 2 3]
 [4 5 6]]
tensor([[1, 2, 3],
        [4, 5, 6]])


In [ ]:
# Tensor Maths or Arthmatic operations 
x = torch.arange(start=10,end=20, step=4)
y = torch.arange(start=5,end=15, step=4)

print(x) 
print(y)

# addition 
  #w1
print('Add:',x+y) # element-wise addition 

  #w2
z1 = torch.empty(3)
torch.add(x,y,out=z1)
print('Using empty :',z1)

 #w3 
print('Direct:',torch.add(x,y))

# subtraction 
print('SUB:',x-y) # element-wise sub

# multiplication 
print('MUL:',x*y) # element-wise Multiplication

# Division
z = x/y
print(z)

tensor([10, 14, 18])
tensor([ 5,  9, 13])
Add: tensor([15, 23, 31])
Using empty : tensor([15., 23., 31.])
Direct: tensor([15, 23, 31])
SUB: tensor([5, 5, 5])
MUL: tensor([ 50, 126, 234])
tensor([2.0000, 1.5556, 1.3846])


In [ ]:
# --> Whenever we see operation having _ that means they are inplace
# Inplace

z = torch.ones(3)
# way1 
print(z)
z.add_(x)
print(z)

# way2 inplace
z +=x

# Power , Exponential 
z = x.pow(2)  #same as below
z = x**2
print(z)

# Comparison
z = x >0
print(z)

tensor([1., 1., 1.])
tensor([11., 15., 19.])
tensor([100, 196, 324])
tensor([True, True, True])


In [ ]:
# Matrix Multiplication 
x1 = torch.rand(size=(3,5))
x2 = torch.rand(size=(5,3))

x1 @ x2

tensor([[1.1097, 1.4858, 1.4478],
        [0.7917, 1.2992, 1.2892],
        [0.8840, 0.9720, 0.7377]])

In [ ]:
x1.matmul(x2)

tensor([[1.1097, 1.4858, 1.4478],
        [0.7917, 1.2992, 1.2892],
        [0.8840, 0.9720, 0.7377]])

In [ ]:
# Matrix exponential
m1 = torch.rand((5,5))
m1.matrix_exp()

tensor([[2.6945, 2.1034, 1.6043, 1.7543, 1.6884],
        [1.4434, 2.7699, 1.4889, 1.3319, 1.2115],
        [1.7355, 1.9529, 2.1452, 1.4329, 1.5779],
        [1.9416, 2.4745, 1.5017, 2.6717, 1.2627],
        [2.6517, 3.2420, 2.3756, 2.6051, 3.0051]])

In [ ]:
m1.matrix_power(3)

tensor([[2.4968, 3.0594, 2.1824, 2.3212, 2.0624],
        [1.9984, 2.4564, 1.8004, 1.9072, 1.6452],
        [2.2896, 2.7681, 1.8537, 2.0444, 1.8546],
        [2.4536, 2.9751, 2.0883, 2.2620, 2.0180],
        [3.5527, 4.3520, 3.1528, 3.3420, 2.9386]])

In [ ]:
# Dot Product 
 # --> sum of element wise multiplication
result = torch.dot(x,y)
print(result)

tensor(410)


In [ ]:
# Batch Matrix Multiplication 
batch = 4
n = 4
m = 5
p = 4

m1 = torch.rand(size=(batch,n,m))
m2 = torch.rand(size=(batch,m,p))

print('M1 : ',m1)
print('M2 : ',m2)
output = torch.bmm(m1,m2)
print('Output : ',output)

M1 :  tensor([[[0.9254, 0.7631, 0.4458, 0.8146, 0.0154],
         [0.7727, 0.1329, 0.1616, 0.9335, 0.8711],
         [0.2813, 0.6974, 0.3604, 0.6869, 0.5708],
         [0.2151, 0.0853, 0.8987, 0.4211, 0.9426]],

        [[0.8304, 0.0430, 0.5054, 0.5621, 0.3544],
         [0.9936, 0.2839, 0.6399, 0.9888, 0.5669],
         [0.3605, 0.8845, 0.0958, 0.8994, 0.8688],
         [0.9697, 0.6366, 0.6689, 0.9893, 0.3641]],

        [[0.6791, 0.9650, 0.5007, 0.9848, 0.4178],
         [0.2683, 0.6439, 0.4154, 0.8572, 0.6418],
         [0.7739, 0.9466, 0.9649, 0.0526, 0.9795],
         [0.9463, 0.3175, 0.1716, 0.1316, 0.2422]],

        [[0.5349, 0.8729, 0.0140, 0.9535, 0.3146],
         [0.3774, 0.6195, 0.6462, 0.8991, 0.6417],
         [0.6255, 0.8025, 0.4103, 0.9140, 0.7422],
         [0.3782, 0.9151, 0.8375, 0.1348, 0.6414]]])
M2 :  tensor([[[0.4604, 0.9350, 0.6088, 0.5748],
         [0.8378, 0.1836, 0.5748, 0.8236],
         [0.2249, 0.5985, 0.8589, 0.8251],
         [0.7501, 0.0646, 0.1320, 0

In [ ]:
# Broadcasting
x1 = torch.ones((5,5))
x2 = torch.ones((1,5))

x1 - x2 # matrix - vector

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [ ]:
# Other usefull Tensor Operations 
x1 = torch.ones((5,5))
torch.sum(x1)

tensor(25.)

In [ ]:
x1 = torch.rand((5,5))
print(x1)
print(torch.max(x1,dim = 1)) # return values , indices 
print(torch.min(x1,dim = 1))

tensor([[0.4422, 0.7849, 0.5637, 0.7769, 0.7643],
        [0.2406, 0.3861, 0.3265, 0.8924, 0.7846],
        [0.6301, 0.2687, 0.9835, 0.9999, 0.6946],
        [0.9277, 0.3555, 0.9738, 0.9907, 0.2926],
        [0.6356, 0.4092, 0.0846, 0.4082, 0.4947]])
torch.return_types.max(
values=tensor([0.7849, 0.8924, 0.9999, 0.9907, 0.6356]),
indices=tensor([1, 3, 3, 3, 0]))
torch.return_types.min(
values=tensor([0.4422, 0.2406, 0.2687, 0.2926, 0.0846]),
indices=tensor([0, 0, 1, 4, 2]))


In [ ]:
torch.abs(x1) # abs value

tensor([[0.4422, 0.7849, 0.5637, 0.7769, 0.7643],
        [0.2406, 0.3861, 0.3265, 0.8924, 0.7846],
        [0.6301, 0.2687, 0.9835, 0.9999, 0.6946],
        [0.9277, 0.3555, 0.9738, 0.9907, 0.2926],
        [0.6356, 0.4092, 0.0846, 0.4082, 0.4947]])

In [ ]:
torch.argmax(x1)

tensor(13)

In [ ]:
torch.argmin(x1)

tensor(22)

In [ ]:
torch.mean(x1)

tensor(0.6045)

In [ ]:
torch.eq(x,y)

tensor([False, False, False])

In [ ]:
torch.sort(x)  # return sorted values , and indices

torch.return_types.sort(values=tensor([10, 14, 18]), indices=tensor([0, 1, 2]))

In [ ]:
# if values less than zero then it will put that 0
torch.clamp(x,min=0)

tensor([10, 14, 18])

In [ ]:
# relu is a special value of clamp
torch.clamp(x,min=13)

tensor([13, 14, 18])

In [ ]:
# any value 1
# all values 1 
torch.any(x)

tensor(True)

In [ ]:
torch.all(x)

tensor(True)

In [ ]:
# Indexing in the tensor 

batch = 10
features = 25
x = torch.rand(size=(batch,features))
#print(x)
# rows , cols
# x[start:stop:step,start:stop:step]
print(x[0,10:])
print(x[:,0])
print(x[0:2,0:2])
x[0,0] = 1000


tensor([0.9016, 0.7278, 0.8068, 0.4291, 0.0132, 0.4544, 0.3469, 0.1188, 0.9456,
        0.6282, 0.5532, 0.7360, 0.6369, 0.7653, 0.6158])
tensor([0.7568, 0.3038, 0.1760, 0.7897, 0.7653, 0.3336, 0.6823, 0.1100, 0.9755,
        0.8183])
tensor([[0.7568, 0.6877],
        [0.3038, 0.2388]])


tensor([[1.0000e+03, 6.8765e-01, 4.1086e-01, 6.4282e-01, 6.7555e-01, 1.8083e-01,
         7.7711e-01, 5.2241e-01, 3.2136e-01, 9.4001e-01, 9.0156e-01, 7.2784e-01,
         8.0675e-01, 4.2912e-01, 1.3198e-02, 4.5435e-01, 3.4687e-01, 1.1882e-01,
         9.4559e-01, 6.2821e-01, 5.5317e-01, 7.3601e-01, 6.3690e-01, 7.6527e-01,
         6.1582e-01],
        [3.0380e-01, 2.3876e-01, 1.9746e-01, 9.8132e-02, 8.5306e-02, 8.7092e-01,
         4.6283e-01, 7.4097e-01, 3.1838e-01, 9.4429e-01, 8.4652e-01, 8.5745e-02,
         4.7379e-01, 7.5662e-01, 6.8196e-01, 7.9146e-01, 5.4373e-01, 8.7706e-01,
         5.6335e-01, 4.0479e-01, 1.2855e-01, 6.9984e-01, 4.2106e-01, 1.5898e-01,
         7.2535e-01],
        [1.7603e-01, 3.2973e-01, 3.8628e-01, 5.2676e-01, 8.7118e-01, 5.2162e-01,
         9.7718e-01, 9.9805e-01, 1.2840e-01, 5.5083e-01, 8.7203e-01, 4.8735e-01,
         8.3252e-01, 3.5506e-01, 7.1784e-01, 3.6339e-01, 4.0818e-01, 9.8807e-01,
         8.5299e-01, 7.5678e-01, 2.5481e-01, 8.1315e-01, 2.6594e-

In [ ]:
# Advanced Indexing 
#x[(x>11 )| (x<15)]
print(x[x.remainder(2)==0])
print(x.unique()[:5])
print(torch.where(x<5 ,0 , 1 )[:1,:1]) # where x, y
print(x.ndimension()) # gives dim
print(x.numel())  # count number of elements in x

tensor([1000.])
tensor([0.0061, 0.0132, 0.0292, 0.0304, 0.0326])
tensor([[1]])
2
250


In [ ]:
# Reshaping of Tensor
x = torch.arange(9)
print(x)
print(x.view(3,3))    # continous data to reshape
print(x.reshape(3,3)) # reshape any kind of data 
print(x.reshape(3,3).t()) # traspose of values

# concatination
x1 = torch.rand((2,5))
x2 = torch.rand((2,5))

print(torch.cat((x1,x2),dim=1)) # dim 0  add rows , dim 1 add cols 


# Flatten tensor
print(x1.shape)
x1.view(-1).shape

# batch Flatten
batch = 16
torch.rand((batch,2,5)).view((batch,-1))

# Reshape manually 
x1.permute(1,0)  # index position of dimen



tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([[0.3794, 0.2874, 0.0957, 0.0898, 0.6790, 0.8288, 0.6315, 0.5135, 0.6290,
         0.4043],
        [0.2715, 0.9132, 0.0567, 0.4575, 0.8356, 0.9800, 0.9969, 0.1976, 0.9927,
         0.8371]])
torch.Size([2, 5])


tensor([[0.3794, 0.2715],
        [0.2874, 0.9132],
        [0.0957, 0.0567],
        [0.0898, 0.4575],
        [0.6790, 0.8356]])

2